version: "3.9"

services:
  web:
    build: .
    container_name: fastapi
    restart: always
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000 
    ports:
      - 8000:8000
    volumes:
      - ./app:/code/
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres_database
    restart: always
    env_file:
      - .env

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin_for_postgres
  #   restart: always
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@admin.com
  #     - PGADMIN_DEFAULT_PASSWORD=root
  #   ports:
  #     - 5050:80
  #   depends_on:
  #     - db


